### ISSUE TITLE
Cannot execute binary file (in macOS terminal)

### ISSUE THREAD

**Issue by ianGre** [arnaucode/goBlockchainDataAnalysis#1]
```
$ ./goBlockchainDataAnalysis -explore
-bash: ./goBlockchainDataAnalysis: cannot execute binary file
```

I guess I'll try another project.

Thanks.

**Comment by arnaucube** [comment]
yes, the published binary is compiled for Linux x86_64 architecture. From a macOS you can compile the binary using `go build`, and this compiled binary will be for the architecture of that macOS.

**Comment by ianGre** [comment]
Cool! Thanks. You've inspired me now to go get go!

**Comment by ianGre** [comment]
> Cool! Thanks. You've inspired me now to go get go!

But "go build" could not find a bunch of dependencies. I'm now trying "$ go get github.com/arnaucube/goBlockchainDataAnalysis".

```
$ go get github.com/arnaucube/goBlockchainDataAnalysis
# github.com/arnaucube/goBlockchainDataAnalysis
../../go/src/github.com/arnaucube/goBlockchainDataAnalysis/exploreBlockchain.go:31:27: cannot use block.Confirmations (type int64) as type uint64 in assignment
```

**Comment by ianGre** [comment]
Evidently go tried to go build. When  I try it again I get the same error message about the block.Confirmations (type int64).

**Comment by ianGre** [comment]
This seems to be related to data structure in mongoModels.go
Confirmations (in BlockModel) is uint64. I'm _pretty sure_ that confirmations can only be a positive integer. 

... I don't know why the error (msg earlier) thinks that newBlock.Confirmations is int64, while it needs to match the data type of block.Confirmations as uint64. I am only seeing uint64 in mongoModels.go, and in exploreBlockchain.go, where the compilation error is found, it creates the newBlock variable using BlockModel. 

... ? ```var newBlock BlockModel``` should correctly set the data types, and the data types of the array `block` is set in ```type AddressModel struct {``` (which takes it from BlockModel).

So, this compiles okay in Linux??

The only thing I can think of is that when the array `block` is invoked in exploreBlockchain.go the declaration found in mongoModels.go (AddressModel struct) has not run or has not been called, unlike the way the array newBlock is declared (in exploreBlockchain.go).

**Comment by ianGre** [comment]
*** I seem to have fixed it by adding ```var block BlockModel``` on the line before ```var newBlock Blockmodel```, but now I just need to deal with the config for my blockchain.

**Comment by arnaucube** [comment]
Great to see that finally you've fixed it. But take in mind that this project is not active. I started the implementation to understand the bitcoin/faircoin data structures, but then stopped implementation due lack of time and being busy with other side projects.
